[db_credentials]
user = "sa"
password = "070999aaaAAA@@@#"
Database="APPNHAOXH"
host = "27.72.163.235,1433"
Driver="SQL Server"
#DB_TOKEN="QuocKhanhAn2024@"
api_key = "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"